version: "3.7"
services:
  make:
    build: .
    entrypoint: make
    volumes:
      - ./typedoc.json:/typedoc.json:ro
      - ./Makefile:/Makefile:ro
      - ./libs:/libs:ro
      - ./source:/source:ro
      - ./docs:/docs # output

  server:
    build: .
    entrypoint: nginx -g "daemon off;"
    volumes:
      - ./docs:/docs:ro
    ports:
      - "12800:80"
